import os
import sys
import re

sys.stdout.reconfigure(encoding='utf-8')
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials

# 사용할 권한 (스코프): 유튜브 업로드 및 조회 권한 포함
SCOPES = [
    'https://www.googleapis.com/auth/youtube.upload',
    'https://www.googleapis.com/auth/youtube.readonly',
    'https://www.googleapis.com/auth/youtube'
]

def get_authenticated_service():
    creds = None
    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json', SCOPES)
    
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not os.path.exists('client_secret.json'):
                print("❌ [업로드 실패] 'client_secret.json' 파일이 존재하지 않습니다.")
                print("   Google Cloud Console에서 OAuth 2.0 자격 증명을 다운로드하여 이 폴더에 넣어주세요.")
                return None
            flow = InstalledAppFlow.from_client_secrets_file('client_secret.json', SCOPES)
            creds = flow.run_local_server(port=0)
            
        with open('token.json', 'w') as token:
            token.write(creds.to_json())
            
    return build('youtube', 'v3', credentials=creds)

def parse_metadata():
    title = "Default AI Music Video"
    description = "Generated by Agent Luna."
    tags = ["lofi", "music", "ai", "study"]
    
    if os.path.exists("lyrics_and_plan.txt"):
        with open("lyrics_and_plan.txt", "r", encoding="utf-8") as f:
            content = f.read()
            
            title_match = re.search(r'\*\*영상의 제목.*?\n\s*\*\*(.*?)\*\*', content, re.IGNORECASE)
            if not title_match:
                title_match = re.search(r'영상의 제목.*?\n.*?(.*?)\n', content, re.IGNORECASE)
                
            desc_match = re.search(r'\*\*영상 설명.*?\n(.*?)(?:\n\n|\n---|\n3\.)', content, re.IGNORECASE | re.DOTALL)
            
            if title_match:
                title = title_match.group(1).strip()
            if desc_match:
                description = desc_match.group(1).strip()
    
    description += "\n\n⚠️ 본 영상의 음악과 이미지는 AI 기술을 활용하여 자동 생성(창작)되었습니다.\n(This video's music and images were created using AI technology.)\n\n#lofi #study #music #chill #AgentLuna"
    
    # 제목이 길어지면 자르기 (유튜브 제한 100자)
    return title[:100], description, tags

def is_already_uploaded(youtube, title):
    """채널의 최근 업로드 리스트를 확인하여 동일한 제목의 비디오가 이미 업로드되어 있는지 체크합니다."""
    try:
        channels_response = youtube.channels().list(
            mine=True,
            part='contentDetails'
        ).execute()
        
        if not channels_response.get('items'):
            return False
            
        uploads_playlist_id = channels_response['items'][0]['contentDetails']['relatedPlaylists']['uploads']
        
        # 최근 15개 업로드 확인
        playlist_response = youtube.playlistItems().list(
            playlistId=uploads_playlist_id,
            part='snippet',
            maxResults=15
        ).execute()
        
        for item in playlist_response.get('items', []):
            existing_title = item['snippet']['title']
            if existing_title.strip() == title.strip():
                return True
        return False
    except Exception as e:
        print(f"⚠️ 중복 조회 중 오류가 발생하여 건너뜁니다: {e}")
        return False

def upload_video(youtube, title, description, tags, file_path, publish_time=None):
    if is_already_uploaded(youtube, title):
        print(f"\n⚠️ [업로드 건너뛰기] 동일한 제목('{title}')의 영상이 이미 유튜브 채널에 업로드되어 있어 업로드를 생략합니다.")
        return
        
    status_msg = f"공개 예약 ({publish_time})" if publish_time else "예약 없음 (비공개)"
    print(f"🎬 업로드 준비 중...\n - 제목: {title}\n - 업로드 상태: {status_msg}\n - 파일: {file_path}")
    
    body = {
        'snippet': {
            'title': title,
            'description': description,
            'tags': tags,
            'categoryId': '10' # 음악 카테고리
        },
        'status': {
            # YouTube API 규칙: publishAt(공개 예약)을 사용하려면 privacyStatus는 반드시 'private'이어야 함.
            # 지정된 publishAt 시간이 되면 자동으로 유튜브가 'public'으로 전환함.
            'privacyStatus': 'private',
            'selfDeclaredMadeForKids': False,
            'containsSyntheticMedia': True
        }
    }
    
    if publish_time:
        body['status']['publishAt'] = publish_time
    
    media = MediaFileUpload(file_path, chunksize=-1, resumable=True)
    request = youtube.videos().insert(
        part=','.join(body.keys()),
        body=body,
        media_body=media
    )
    
    response = None
    print("⏳ 동영상을 유튜브 서버로 전송 중입니다...")
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"진행률: {int(status.progress() * 100)}%")
            
    video_url = f"https://studio.youtube.com/video/{response['id']}/edit"
    
    if publish_time:
        print(f"✅ 성공! 비디오 업로드 완료 (정해진 시간에 '공개'되도록 예약되었습니다: {publish_time})")
    else:
        print(f"✅ 성공! 비디오 업로드 완료 (비공개 상태)")
        
    print(f"🔗 확인 링크: {video_url}")
    
    # 크롬 브라우저로 자동 열기 시도 (Windows 전용 명령어 사용)
    try:
        import os
        os.system(f"start chrome {video_url}")
    except Exception as e:
        print(f"⚠️ 크롬 브라우저 자동 실행에 실패했습니다: {e}")
if __name__ == "__main__":
    import sys
    print("\n--- 🤖 Agent Luna: 유튜브 자동 업로드 모듈 시작 ---")
    youtube = get_authenticated_service()
    
    if youtube:
        title, description, tags = parse_metadata()
        video_file = "video.mp4" # 업로드 타겟 파일
        
        # 메인 스크립트에서 전달한 ISO 8601 포맷 시간 추출
        publish_time = sys.argv[1] if len(sys.argv) > 1 else None
        
        if not os.path.exists(video_file):
            print(f"⚠️ [대기] 타겟 영상 파일('{video_file}')이 없습니다.")
            print("현재 파이프라인이 텍스트 추출로 우회 테스트 중입니다. 실제 업로드를 검증하려면 아무 mp4 영상을 'video.mp4'로 작업 폴더에 넣어주세요.")
        else:
            upload_video(youtube, title, description, tags, video_file, publish_time)
